language: python
sudo: false
dist: xenial
python:
    - "3.5"
    - "3.6"
    - "3.7"

addons:
    apt:
        update: true

before_install:
    - sudo apt-get install -y libxmlsec1-dev

install:
    - pip install tox-travis

script:
    - tox
